import type { ComponentType } from "react";
import {
  SiReact,
  SiNextdotjs,
  SiVite,
  SiTailwindcss,
  SiFramer,
  SiReactrouter,
  SiNodedotjs,
  SiExpress,
  SiFastapi,
  SiFlutter,
  SiDart,
  SiFirebase,
  SiPython,
  SiScikitlearn,
  SiPandas,
  SiNumpy,
  SiOpencv,
  SiTensorflow,
  SiPytorch,
  SiMongodb,
  SiMongoose,
  SiJsonwebtokens,
  SiVercel,
  SiRender,
  SiCloudinary,
  SiGit,
  SiGithub,
  SiCisco,
  SiPostgresql,
  SiMysql,
} from "react-icons/si";
import { Webhook, KeyRound } from "lucide-react";

type IconComponent = ComponentType<any>;

export const skillIcons: Record<string, IconComponent> = {
  React: SiReact,
  "Next.js": SiNextdotjs,
  Vite: SiVite,
  "Tailwind CSS": SiTailwindcss,
  "Framer Motion": SiFramer,
  "React Router": SiReactrouter,
  "Node.js": SiNodedotjs,
  Express: SiExpress,
  FastAPI: SiFastapi,
  "REST APIs": Webhook,
  Flutter: SiFlutter,
  Dart: SiDart,
  Firebase: SiFirebase,
  Python: SiPython,
  "scikit-learn": SiScikitlearn,
  Pandas: SiPandas,
  NumPy: SiNumpy,
  OpenCV: SiOpencv,
  TensorFlow: SiTensorflow,
  PyTorch: SiPytorch,
  MongoDB: SiMongodb,
  Mongoose: SiMongoose,
  JWT: SiJsonwebtokens,
  bcrypt: KeyRound,
  Vercel: SiVercel,
  Render: SiRender,
  Cloudinary: SiCloudinary,
  Git: SiGit,
  GitHub: SiGithub,
  "Git & GitHub": SiGithub, 
  "Cisco Packet Tracer": SiCisco,
  PostgreSQL: SiPostgresql,
  Postgres: SiPostgresql,
  "Postgres SQL": SiPostgresql,
  MySQL: SiMysql,
  "My SQL": SiMysql,
};

export const skillColors: Record<string, string> = {
  React: "#61DAFB",
  "Next.js": "#EDEAE2",
  Vite: "#9135FF",
  "Tailwind CSS": "#06B6D4",
  "Framer Motion": "#0055FF",
  "React Router": "#CA4245",
  "Node.js": "#5FA04E",
  Express: "#EDEAE2",
  FastAPI: "#009688",
  "REST APIs": "#8FA0A3",
  Flutter: "#02569B",
  Dart: "#0175C2",
  Firebase: "#DD2C00",
  Python: "#3776AB",
  "scikit-learn": "#F7931E",
  Pandas: "#EDEAE2",
  NumPy: "#EDEAE2",
  OpenCV: "#5C3EE8",
  TensorFlow: "#FF6F00",
  PyTorch: "#EE4C2C",
  MongoDB: "#47A248",
  Mongoose: "#880000",
  JWT: "#EDEAE2",
  bcrypt: "#8FA0A3",
  Vercel: "#EDEAE2",
  Render: "#EDEAE2",
  Cloudinary: "#3448C5",
  Git: "#F03C2E",
  GitHub: "#EDEAE2",
  "Git & GitHub": "#EDEAE2",
  "Cisco Packet Tracer": "#1BA0D7",
  PostgreSQL: "#4169E1",
  Postgres: "#4169E1",
  "Postgres SQL": "#4169E1",
  MySQL: "#4479A1",
  "My SQL": "#4479A1",
};